name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Replace Firebase Config
        run: |
          sed -i "s/\${{ secrets.FIREBASE_API_KEY }}/${{ secrets.FIREBASE_API_KEY }}/g" firebase-config.js
          sed -i "s/\${{ secrets.FIREBASE_AUTH_DOMAIN }}/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" firebase-config.js
          sed -i "s/\${{ secrets.FIREBASE_PROJECT_ID }}/${{ secrets.FIREBASE_PROJECT_ID }}/g" firebase-config.js
          sed -i "s/\${{ secrets.FIREBASE_STORAGE_BUCKET }}/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" firebase-config.js
          sed -i "s/\${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" firebase-config.js
          sed -i "s/\${{ secrets.FIREBASE_APP_ID }}/${{ secrets.FIREBASE_APP_ID }}/g" firebase-config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: . 